[package]
name = "foo"
version = "0.1.0"
authors = ["Sébastien Lerique <sl@mehho.net>"]
links = "bar"

[lib]
#crate-type = ["cdylib"]
crate-type = ["cdylib", "rlib"]

[dependencies]
#wasm-bindgen = "0.2"
